### PR TITLE
using factory pattern for database connection #106

### PR DESCRIPTION
**Pull request by Sadaf-A**
This PR implements factory pattern for database connection.

### CODE REVIEW

**Comment by grumpyp** [comment]
Hi there, thanks for your contribution. I don't see any improvements to the code nor the factory pattern I was expecting.

Elaborate why I should merge this please.

**Comment by Sadaf-A** [comment]
@grumpyp I'm sorry, actually I'm a beginner I thought I understood factory design pattern and went on to do it. You must be right I'll try to be more careful.

**Comment by grumpyp** [comment]
Hi @Sadaf-A

do you want to keep working on it then or get back here once you feel like tackeling the issue?
There are easier issues to start with I'd say :)

**Comment by Sadaf-A** [comment]
@grumpyp I'd like to try once more

**Pull request closed without merging**
