### PR TITLE
Validate api key before saving config

### PR DESCRIPTION
**Pull request by NikoRaisanen**
#### Invalid api key - exception information is bubbled up to the frontend

Invalid api key
invalidApiKey1

Quota exceeded
invalidApiKey2

#### Valid api key
image

We now make a test api call before saving config to the db. If the test api call fails, we display the ErrorNotification component, otherwise we save the config as normal

### CODE REVIEW

**Comment by NikoRaisanen** [comment]
@grumpyp Let me know if you have any feedback on this PR, I did my best to follow the existing patterns. Once you confirm that this is a valid solution I'd be happy to write some tests for this feature.

**Comment by grumpyp** [comment]
Hi, awesome work. Yes I agree with your idea. Would you be able to add additional information about the `Exception` itself?

**Comment by NikoRaisanen** [comment]
Yup, sounds like a plan 🚀

**Comment by NikoRaisanen** [comment]
This is ready for another review

**Review by grumpyp — APPROVED** [review]
Awesome! Thanks a lot for your contribution!

**Comment by grumpyp** [comment]
Great work 🚀

**Pull request merged**
