### PR TITLE
[V2] Add Docker environment for easy setup of the project

### PR DESCRIPTION
**Pull request by dipta10**
Issue: https://github.com/grumpyp/aixplora/issues/42

- The idea is that someone who needs to set up the project initially they can just run `docker compose up` which should build everything for them
- Since some of us are facing issues installing the front-end, I am trying to move the node_modules folder from the container to the local machine. This way it will help with the IDE/LSP suggestions.
- Doing so actually installs the packages every time when we spin up our container which is clumsy. But the subsequent installations take less time because they're already installed the first time.

Issues:
The application runs but there are some errors in the log
- after running `docker compose up`
  ```
	aix-fe  | > start:preload
	aix-fe  | > cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts
	aix-fe  |
	aix-fe  |
	aix-fe  | > start:main
	aix-fe  | > cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only .
	aix-fe  |
	aix-fe  | Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
	aix-fe  | [electronmon] waiting for a change to restart it
	aix-fe  | [electronmon] app exited with code null, waiting for change to restart it
	aix-fe  | [131:0100/000000.895638:ERROR:zygote_linux.cc(661)] write: Broken pipe (32)
	a
	```
- Navigating to the UI 
  image

Todo
- [x] modify readme files

### CODE REVIEW

**Comment by grumpyp** [comment]
```
[+] Running 3/3
 ⠿ Network aixplora_default  Created                                                                                                                                   0.2s
 ⠿ Container aix-be          Created                                                                                                                                   0.1s
 ⠿ Container aix-fe          Created                                                                                                                                   0.1s
Attaching to aix-be, aix-fe
aix-fe  | node_modules directory exists. Skipping npm install.
aix-fe  | If your dependencies have changed, please remove node_modules folder and run the container
aix-fe  | starting app...
aix-fe  | 
aix-fe  | > start
aix-fe  | > ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer
aix-fe  | 
aix-be  | INFO:     Started server process [1]
aix-be  | INFO:     Waiting for application startup.
aix-be  | INFO:     Application startup complete.
aix-be  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
aix-fe  | 
aix-fe  | > start:renderer
aix-fe  | > cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts
aix-fe  | 
aix-fe  | Starting preload.js builder...
aix-fe  | Starting Main Process...
aix-fe  | <i> [webpack-dev-server] Project is running at:
aix-fe  | <i> [webpack-dev-server] Loopback: http://localhost:1212/
aix-fe  | <i> [webpack-dev-server] Content not from webpack is served from '/usr/src/app/public' directory
aix-fe  | <i> [webpack-dev-server] 404s will fallback to '/index.html'
aix-fe  | 
aix-fe  | > start:preload
aix-fe  | > cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts
aix-fe  | 
aix-fe  | 
aix-fe  | > start:main
aix-fe  | > cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only .
aix-fe  | 
aix-fe  | /usr/src/app/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron: 1: Syntax error: "(" unexpected
aix-fe  | [electronmon] app exited with code 2, waiting for change to restart it
aix-fe  | [electronmon] waiting for a change to restart it
```

this one doesn't start the frontend

**Comment by samahrens** [comment]
Worked for me on Windows 10. Got some startup errors on the frontend, but it seems the app is unaffected by them. Also, "npm install frontend" didn't work for me, so i did "cd frontend" and then "npm install" and it worked fine
errr

**Comment by grumpyp** [comment]
Hi @dipta10 maybe we merge #76 in here and then merge it to main?

Seems to be working. What do you think? Also in terms of the seperation React/ElectronJS for the docker specific version?

**Comment by dipta10** [comment]
hey @grumpyp yes, we can do that.
But are you sure we should merge this? As I've mentioned earlier, we'll have to either
- remove node_modules files to re-install a dependency
- or remove the need to change anything, I can add `npm install` in the startup script. that way there is no need to remove the node_modules folder, but it will make the bootup process a little slower.

**Review by grumpyp — APPROVED** [review]

**Comment by grumpyp** [comment]
awesome work thanks a bunch!! Now everyone is enabled to use AIxplora :)

**Pull request merged**
